version: "3.8"

services:
  mysql-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: trochez-project
    volumes:
      - ./volume/trochez-project:/var/lib/mysql
    ports:
      - 3306:3306
